//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/4/2019 3:34:12 PM
namespace RedoakAdmin.Models.Roi.Data
{
    /// <summary>
    /// There are no comments for TestSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TestSingle")]
    public partial class TestSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Test>
    {
        /// <summary>
        /// Initialize a new TestSingle object.
        /// </summary>
        public TestSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new TestSingle object.
        /// </summary>
        public TestSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new TestSingle object.
        /// </summary>
        public TestSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Test> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Test in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Test")]
    public partial class Test : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Test object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="legacyKey">Initial value of LegacyKey.</param>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="subjectId">Initial value of SubjectId.</param>
        /// <param name="deviceId">Initial value of DeviceId.</param>
        /// <param name="companyId">Initial value of CompanyId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static Test CreateTest(global::System.Guid ID, 
                    global::System.DateTimeOffset date, 
                    long legacyKey, 
                    global::System.Guid userId, 
                    global::System.Guid subjectId, 
                    global::System.Guid deviceId, 
                    global::System.Guid companyId)
        {
            Test test = new Test();
            test.Id = ID;
            test.Date = date;
            test.LegacyKey = legacyKey;
            test.UserId = userId;
            test.SubjectId = subjectId;
            test.DeviceId = deviceId;
            test.CompanyId = companyId;
            return test;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Date")]
        public global::System.DateTimeOffset Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.DateTimeOffset _Date;
        partial void OnDateChanging(global::System.DateTimeOffset value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property LegacyKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LegacyKey")]
        public long LegacyKey
        {
            get
            {
                return this._LegacyKey;
            }
            set
            {
                this.OnLegacyKeyChanging(value);
                this._LegacyKey = value;
                this.OnLegacyKeyChanged();
                this.OnPropertyChanged("LegacyKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private long _LegacyKey;
        partial void OnLegacyKeyChanging(long value);
        partial void OnLegacyKeyChanged();
        /// <summary>
        /// There are no comments for Property TestHistory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TestHistory")]
        public string TestHistory
        {
            get
            {
                return this._TestHistory;
            }
            set
            {
                this.OnTestHistoryChanging(value);
                this._TestHistory = value;
                this.OnTestHistoryChanged();
                this.OnPropertyChanged("TestHistory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _TestHistory;
        partial void OnTestHistoryChanging(string value);
        partial void OnTestHistoryChanged();
        /// <summary>
        /// There are no comments for Property SubjectHistory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SubjectHistory")]
        public string SubjectHistory
        {
            get
            {
                return this._SubjectHistory;
            }
            set
            {
                this.OnSubjectHistoryChanging(value);
                this._SubjectHistory = value;
                this.OnSubjectHistoryChanged();
                this.OnPropertyChanged("SubjectHistory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _SubjectHistory;
        partial void OnSubjectHistoryChanging(string value);
        partial void OnSubjectHistoryChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserId")]
        public global::System.Guid UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property SubjectId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SubjectId")]
        public global::System.Guid SubjectId
        {
            get
            {
                return this._SubjectId;
            }
            set
            {
                this.OnSubjectIdChanging(value);
                this._SubjectId = value;
                this.OnSubjectIdChanged();
                this.OnPropertyChanged("SubjectId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _SubjectId;
        partial void OnSubjectIdChanging(global::System.Guid value);
        partial void OnSubjectIdChanged();
        /// <summary>
        /// There are no comments for Property DeviceId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DeviceId")]
        public global::System.Guid DeviceId
        {
            get
            {
                return this._DeviceId;
            }
            set
            {
                this.OnDeviceIdChanging(value);
                this._DeviceId = value;
                this.OnDeviceIdChanged();
                this.OnPropertyChanged("DeviceId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _DeviceId;
        partial void OnDeviceIdChanging(global::System.Guid value);
        partial void OnDeviceIdChanged();
        /// <summary>
        /// There are no comments for Property CompanyId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CompanyId")]
        public global::System.Guid CompanyId
        {
            get
            {
                return this._CompanyId;
            }
            set
            {
                this.OnCompanyIdChanging(value);
                this._CompanyId = value;
                this.OnCompanyIdChanged();
                this.OnPropertyChanged("CompanyId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _CompanyId;
        partial void OnCompanyIdChanging(global::System.Guid value);
        partial void OnCompanyIdChanged();
        /// <summary>
        /// There are no comments for Property LastUpdate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastUpdate")]
        public global::System.Nullable<global::System.DateTimeOffset> LastUpdate
        {
            get
            {
                return this._LastUpdate;
            }
            set
            {
                this.OnLastUpdateChanging(value);
                this._LastUpdate = value;
                this.OnLastUpdateChanged();
                this.OnPropertyChanged("LastUpdate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastUpdate;
        partial void OnLastUpdateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastUpdateChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CompanySingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CompanySingle")]
    public partial class CompanySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Company>
    {
        /// <summary>
        /// Initialize a new CompanySingle object.
        /// </summary>
        public CompanySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CompanySingle object.
        /// </summary>
        public CompanySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CompanySingle object.
        /// </summary>
        public CompanySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Company> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Company in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Company")]
    public partial class Company : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="isActive">Initial value of IsActive.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static Company CreateCompany(global::System.Guid ID, bool isActive)
        {
            Company company = new Company();
            company.Id = ID;
            company.IsActive = isActive;
            return company;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Address")]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
                this.OnPropertyChanged("Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("City")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("State")]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this._State = value;
                this.OnStateChanged();
                this.OnPropertyChanged("State");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _State;
        partial void OnStateChanging(string value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Property Zip in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Zip")]
        public string Zip
        {
            get
            {
                return this._Zip;
            }
            set
            {
                this.OnZipChanging(value);
                this._Zip = value;
                this.OnZipChanged();
                this.OnPropertyChanged("Zip");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Zip;
        partial void OnZipChanging(string value);
        partial void OnZipChanged();
        /// <summary>
        /// There are no comments for Property IsActive in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsActive")]
        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this.OnIsActiveChanging(value);
                this._IsActive = value;
                this.OnIsActiveChanged();
                this.OnPropertyChanged("IsActive");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private bool _IsActive;
        partial void OnIsActiveChanging(bool value);
        partial void OnIsActiveChanged();
        /// <summary>
        /// There are no comments for Property LastUpdate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastUpdate")]
        public global::System.Nullable<global::System.DateTimeOffset> LastUpdate
        {
            get
            {
                return this._LastUpdate;
            }
            set
            {
                this.OnLastUpdateChanging(value);
                this._LastUpdate = value;
                this.OnLastUpdateChanged();
                this.OnPropertyChanged("LastUpdate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastUpdate;
        partial void OnLastUpdateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastUpdateChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SubjectSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SubjectSingle")]
    public partial class SubjectSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Subject>
    {
        /// <summary>
        /// Initialize a new SubjectSingle object.
        /// </summary>
        public SubjectSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new SubjectSingle object.
        /// </summary>
        public SubjectSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new SubjectSingle object.
        /// </summary>
        public SubjectSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Subject> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Subject in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Subject")]
    public partial class Subject : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Subject object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="dob">Initial value of Dob.</param>
        /// <param name="companyId">Initial value of CompanyId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static Subject CreateSubject(global::System.Guid ID, global::System.DateTimeOffset dob, global::System.Guid companyId)
        {
            Subject subject = new Subject();
            subject.Id = ID;
            subject.Dob = dob;
            subject.CompanyId = companyId;
            return subject;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Dob in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Dob")]
        public global::System.DateTimeOffset Dob
        {
            get
            {
                return this._Dob;
            }
            set
            {
                this.OnDobChanging(value);
                this._Dob = value;
                this.OnDobChanged();
                this.OnPropertyChanged("Dob");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.DateTimeOffset _Dob;
        partial void OnDobChanging(global::System.DateTimeOffset value);
        partial void OnDobChanged();
        /// <summary>
        /// There are no comments for Property Social in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Social")]
        public string Social
        {
            get
            {
                return this._Social;
            }
            set
            {
                this.OnSocialChanging(value);
                this._Social = value;
                this.OnSocialChanged();
                this.OnPropertyChanged("Social");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Social;
        partial void OnSocialChanging(string value);
        partial void OnSocialChanged();
        /// <summary>
        /// There are no comments for Property AltId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AltId")]
        public string AltId
        {
            get
            {
                return this._AltId;
            }
            set
            {
                this.OnAltIdChanging(value);
                this._AltId = value;
                this.OnAltIdChanged();
                this.OnPropertyChanged("AltId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _AltId;
        partial void OnAltIdChanging(string value);
        partial void OnAltIdChanged();
        /// <summary>
        /// There are no comments for Property Uuid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Uuid")]
        public string Uuid
        {
            get
            {
                return this._Uuid;
            }
            set
            {
                this.OnUuidChanging(value);
                this._Uuid = value;
                this.OnUuidChanged();
                this.OnPropertyChanged("Uuid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Uuid;
        partial void OnUuidChanging(string value);
        partial void OnUuidChanged();
        /// <summary>
        /// There are no comments for Property CompanyId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CompanyId")]
        public global::System.Guid CompanyId
        {
            get
            {
                return this._CompanyId;
            }
            set
            {
                this.OnCompanyIdChanging(value);
                this._CompanyId = value;
                this.OnCompanyIdChanged();
                this.OnPropertyChanged("CompanyId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _CompanyId;
        partial void OnCompanyIdChanging(global::System.Guid value);
        partial void OnCompanyIdChanged();
        /// <summary>
        /// There are no comments for Property LastUpdate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastUpdate")]
        public global::System.Nullable<global::System.DateTimeOffset> LastUpdate
        {
            get
            {
                return this._LastUpdate;
            }
            set
            {
                this.OnLastUpdateChanging(value);
                this._LastUpdate = value;
                this.OnLastUpdateChanged();
                this.OnPropertyChanged("LastUpdate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastUpdate;
        partial void OnLastUpdateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastUpdateChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DeviceSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DeviceSingle")]
    public partial class DeviceSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Device>
    {
        /// <summary>
        /// Initialize a new DeviceSingle object.
        /// </summary>
        public DeviceSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DeviceSingle object.
        /// </summary>
        public DeviceSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DeviceSingle object.
        /// </summary>
        public DeviceSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Device> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Device in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Device")]
    public partial class Device : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Device object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="thumbZeroRaw">Initial value of ThumbZeroRaw.</param>
        /// <param name="thumbMaxRaw">Initial value of ThumbMaxRaw.</param>
        /// <param name="thumbMaxLbs">Initial value of ThumbMaxLbs.</param>
        /// <param name="indexZeroRaw">Initial value of IndexZeroRaw.</param>
        /// <param name="indexMaxRaw">Initial value of IndexMaxRaw.</param>
        /// <param name="indexMaxLbs">Initial value of IndexMaxLbs.</param>
        /// <param name="pinkyZeroRaw">Initial value of PinkyZeroRaw.</param>
        /// <param name="pinkyMaxRaw">Initial value of PinkyMaxRaw.</param>
        /// <param name="pinkyMaxLbs">Initial value of PinkyMaxLbs.</param>
        /// <param name="companyId">Initial value of CompanyId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static Device CreateDevice(global::System.Guid ID, 
                    global::RedoakAdmin.Models.Roi.Data.DeviceStatus status, 
                    decimal thumbZeroRaw, 
                    decimal thumbMaxRaw, 
                    decimal thumbMaxLbs, 
                    decimal indexZeroRaw, 
                    decimal indexMaxRaw, 
                    decimal indexMaxLbs, 
                    decimal pinkyZeroRaw, 
                    decimal pinkyMaxRaw, 
                    decimal pinkyMaxLbs, 
                    global::System.Guid companyId)
        {
            Device device = new Device();
            device.Id = ID;
            device.Status = status;
            device.ThumbZeroRaw = thumbZeroRaw;
            device.ThumbMaxRaw = thumbMaxRaw;
            device.ThumbMaxLbs = thumbMaxLbs;
            device.IndexZeroRaw = indexZeroRaw;
            device.IndexMaxRaw = indexMaxRaw;
            device.IndexMaxLbs = indexMaxLbs;
            device.PinkyZeroRaw = pinkyZeroRaw;
            device.PinkyMaxRaw = pinkyMaxRaw;
            device.PinkyMaxLbs = pinkyMaxLbs;
            device.CompanyId = companyId;
            return device;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property SerialId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("SerialId")]
        public string SerialId
        {
            get
            {
                return this._SerialId;
            }
            set
            {
                this.OnSerialIdChanging(value);
                this._SerialId = value;
                this.OnSerialIdChanged();
                this.OnPropertyChanged("SerialId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _SerialId;
        partial void OnSerialIdChanging(string value);
        partial void OnSerialIdChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Status")]
        public global::RedoakAdmin.Models.Roi.Data.DeviceStatus Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::RedoakAdmin.Models.Roi.Data.DeviceStatus _Status;
        partial void OnStatusChanging(global::RedoakAdmin.Models.Roi.Data.DeviceStatus value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property ThumbZeroRaw in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ThumbZeroRaw")]
        public decimal ThumbZeroRaw
        {
            get
            {
                return this._ThumbZeroRaw;
            }
            set
            {
                this.OnThumbZeroRawChanging(value);
                this._ThumbZeroRaw = value;
                this.OnThumbZeroRawChanged();
                this.OnPropertyChanged("ThumbZeroRaw");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private decimal _ThumbZeroRaw;
        partial void OnThumbZeroRawChanging(decimal value);
        partial void OnThumbZeroRawChanged();
        /// <summary>
        /// There are no comments for Property ThumbMaxRaw in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ThumbMaxRaw")]
        public decimal ThumbMaxRaw
        {
            get
            {
                return this._ThumbMaxRaw;
            }
            set
            {
                this.OnThumbMaxRawChanging(value);
                this._ThumbMaxRaw = value;
                this.OnThumbMaxRawChanged();
                this.OnPropertyChanged("ThumbMaxRaw");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private decimal _ThumbMaxRaw;
        partial void OnThumbMaxRawChanging(decimal value);
        partial void OnThumbMaxRawChanged();
        /// <summary>
        /// There are no comments for Property ThumbMaxLbs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ThumbMaxLbs")]
        public decimal ThumbMaxLbs
        {
            get
            {
                return this._ThumbMaxLbs;
            }
            set
            {
                this.OnThumbMaxLbsChanging(value);
                this._ThumbMaxLbs = value;
                this.OnThumbMaxLbsChanged();
                this.OnPropertyChanged("ThumbMaxLbs");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private decimal _ThumbMaxLbs;
        partial void OnThumbMaxLbsChanging(decimal value);
        partial void OnThumbMaxLbsChanged();
        /// <summary>
        /// There are no comments for Property IndexZeroRaw in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IndexZeroRaw")]
        public decimal IndexZeroRaw
        {
            get
            {
                return this._IndexZeroRaw;
            }
            set
            {
                this.OnIndexZeroRawChanging(value);
                this._IndexZeroRaw = value;
                this.OnIndexZeroRawChanged();
                this.OnPropertyChanged("IndexZeroRaw");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private decimal _IndexZeroRaw;
        partial void OnIndexZeroRawChanging(decimal value);
        partial void OnIndexZeroRawChanged();
        /// <summary>
        /// There are no comments for Property IndexMaxRaw in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IndexMaxRaw")]
        public decimal IndexMaxRaw
        {
            get
            {
                return this._IndexMaxRaw;
            }
            set
            {
                this.OnIndexMaxRawChanging(value);
                this._IndexMaxRaw = value;
                this.OnIndexMaxRawChanged();
                this.OnPropertyChanged("IndexMaxRaw");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private decimal _IndexMaxRaw;
        partial void OnIndexMaxRawChanging(decimal value);
        partial void OnIndexMaxRawChanged();
        /// <summary>
        /// There are no comments for Property IndexMaxLbs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IndexMaxLbs")]
        public decimal IndexMaxLbs
        {
            get
            {
                return this._IndexMaxLbs;
            }
            set
            {
                this.OnIndexMaxLbsChanging(value);
                this._IndexMaxLbs = value;
                this.OnIndexMaxLbsChanged();
                this.OnPropertyChanged("IndexMaxLbs");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private decimal _IndexMaxLbs;
        partial void OnIndexMaxLbsChanging(decimal value);
        partial void OnIndexMaxLbsChanged();
        /// <summary>
        /// There are no comments for Property PinkyZeroRaw in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PinkyZeroRaw")]
        public decimal PinkyZeroRaw
        {
            get
            {
                return this._PinkyZeroRaw;
            }
            set
            {
                this.OnPinkyZeroRawChanging(value);
                this._PinkyZeroRaw = value;
                this.OnPinkyZeroRawChanged();
                this.OnPropertyChanged("PinkyZeroRaw");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private decimal _PinkyZeroRaw;
        partial void OnPinkyZeroRawChanging(decimal value);
        partial void OnPinkyZeroRawChanged();
        /// <summary>
        /// There are no comments for Property PinkyMaxRaw in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PinkyMaxRaw")]
        public decimal PinkyMaxRaw
        {
            get
            {
                return this._PinkyMaxRaw;
            }
            set
            {
                this.OnPinkyMaxRawChanging(value);
                this._PinkyMaxRaw = value;
                this.OnPinkyMaxRawChanged();
                this.OnPropertyChanged("PinkyMaxRaw");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private decimal _PinkyMaxRaw;
        partial void OnPinkyMaxRawChanging(decimal value);
        partial void OnPinkyMaxRawChanged();
        /// <summary>
        /// There are no comments for Property PinkyMaxLbs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PinkyMaxLbs")]
        public decimal PinkyMaxLbs
        {
            get
            {
                return this._PinkyMaxLbs;
            }
            set
            {
                this.OnPinkyMaxLbsChanging(value);
                this._PinkyMaxLbs = value;
                this.OnPinkyMaxLbsChanged();
                this.OnPropertyChanged("PinkyMaxLbs");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private decimal _PinkyMaxLbs;
        partial void OnPinkyMaxLbsChanging(decimal value);
        partial void OnPinkyMaxLbsChanged();
        /// <summary>
        /// There are no comments for Property CompanyId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CompanyId")]
        public global::System.Guid CompanyId
        {
            get
            {
                return this._CompanyId;
            }
            set
            {
                this.OnCompanyIdChanging(value);
                this._CompanyId = value;
                this.OnCompanyIdChanged();
                this.OnPropertyChanged("CompanyId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _CompanyId;
        partial void OnCompanyIdChanging(global::System.Guid value);
        partial void OnCompanyIdChanged();
        /// <summary>
        /// There are no comments for Property LastUpdate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastUpdate")]
        public global::System.Nullable<global::System.DateTimeOffset> LastUpdate
        {
            get
            {
                return this._LastUpdate;
            }
            set
            {
                this.OnLastUpdateChanging(value);
                this._LastUpdate = value;
                this.OnLastUpdateChanged();
                this.OnPropertyChanged("LastUpdate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastUpdate;
        partial void OnLastUpdateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastUpdateChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for UserSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("UserSingle")]
    public partial class UserSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<User>
    {
        /// <summary>
        /// Initialize a new UserSingle object.
        /// </summary>
        public UserSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new UserSingle object.
        /// </summary>
        public UserSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new UserSingle object.
        /// </summary>
        public UserSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<User> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("User")]
    public partial class User : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="isActive">Initial value of IsActive.</param>
        /// <param name="companyId">Initial value of CompanyId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static User CreateUser(global::System.Guid ID, bool isActive, global::System.Guid companyId)
        {
            User user = new User();
            user.Id = ID;
            user.IsActive = isActive;
            user.CompanyId = companyId;
            return user;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Password")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property IsActive in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("IsActive")]
        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this.OnIsActiveChanging(value);
                this._IsActive = value;
                this.OnIsActiveChanged();
                this.OnPropertyChanged("IsActive");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private bool _IsActive;
        partial void OnIsActiveChanging(bool value);
        partial void OnIsActiveChanged();
        /// <summary>
        /// There are no comments for Property CompanyId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CompanyId")]
        public global::System.Guid CompanyId
        {
            get
            {
                return this._CompanyId;
            }
            set
            {
                this.OnCompanyIdChanging(value);
                this._CompanyId = value;
                this.OnCompanyIdChanged();
                this.OnPropertyChanged("CompanyId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Guid _CompanyId;
        partial void OnCompanyIdChanging(global::System.Guid value);
        partial void OnCompanyIdChanged();
        /// <summary>
        /// There are no comments for Property LastUpdate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastUpdate")]
        public global::System.Nullable<global::System.DateTimeOffset> LastUpdate
        {
            get
            {
                return this._LastUpdate;
            }
            set
            {
                this.OnLastUpdateChanging(value);
                this._LastUpdate = value;
                this.OnLastUpdateChanged();
                this.OnPropertyChanged("LastUpdate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastUpdate;
        partial void OnLastUpdateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastUpdateChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DeviceStatus in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DeviceStatus")]
    public enum DeviceStatus
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Disabled")]
        Disabled = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Active")]
        Active = 1
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::RedoakAdmin.Models.Roi.Data.Test as global::RedoakAdmin.Models.Roi.Data.TestSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::RedoakAdmin.Models.Roi.Data.TestSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Test> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::RedoakAdmin.Models.Roi.Data.TestSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::RedoakAdmin.Models.Roi.Data.Test as global::RedoakAdmin.Models.Roi.Data.TestSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::RedoakAdmin.Models.Roi.Data.TestSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Test> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::RedoakAdmin.Models.Roi.Data.TestSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::RedoakAdmin.Models.Roi.Data.Company as global::RedoakAdmin.Models.Roi.Data.CompanySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::RedoakAdmin.Models.Roi.Data.CompanySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Company> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::RedoakAdmin.Models.Roi.Data.CompanySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::RedoakAdmin.Models.Roi.Data.Company as global::RedoakAdmin.Models.Roi.Data.CompanySingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::RedoakAdmin.Models.Roi.Data.CompanySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Company> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::RedoakAdmin.Models.Roi.Data.CompanySingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::RedoakAdmin.Models.Roi.Data.Subject as global::RedoakAdmin.Models.Roi.Data.SubjectSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::RedoakAdmin.Models.Roi.Data.SubjectSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Subject> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::RedoakAdmin.Models.Roi.Data.SubjectSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::RedoakAdmin.Models.Roi.Data.Subject as global::RedoakAdmin.Models.Roi.Data.SubjectSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::RedoakAdmin.Models.Roi.Data.SubjectSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Subject> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::RedoakAdmin.Models.Roi.Data.SubjectSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::RedoakAdmin.Models.Roi.Data.Device as global::RedoakAdmin.Models.Roi.Data.DeviceSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::RedoakAdmin.Models.Roi.Data.DeviceSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Device> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::RedoakAdmin.Models.Roi.Data.DeviceSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::RedoakAdmin.Models.Roi.Data.Device as global::RedoakAdmin.Models.Roi.Data.DeviceSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::RedoakAdmin.Models.Roi.Data.DeviceSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Device> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::RedoakAdmin.Models.Roi.Data.DeviceSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::RedoakAdmin.Models.Roi.Data.User as global::RedoakAdmin.Models.Roi.Data.UserSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::RedoakAdmin.Models.Roi.Data.UserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.User> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::RedoakAdmin.Models.Roi.Data.UserSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::RedoakAdmin.Models.Roi.Data.User as global::RedoakAdmin.Models.Roi.Data.UserSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::RedoakAdmin.Models.Roi.Data.UserSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.User> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::RedoakAdmin.Models.Roi.Data.UserSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace RedoakAdmin.Models.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Roi.Data", "RedoakAdmin.Models.Roi.Data");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "RedoakAdmin.Models.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("RedoakAdmin.Models.Roi.Data", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Roi.Data.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Roi.Data.", clientType.Name);
            }
            if (clientType.Namespace.Equals("RedoakAdmin.Models.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Tests in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Tests")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Test> Tests
        {
            get
            {
                if ((this._Tests == null))
                {
                    this._Tests = base.CreateQuery<global::RedoakAdmin.Models.Roi.Data.Test>("Tests");
                }
                return this._Tests;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Test> _Tests;
        /// <summary>
        /// There are no comments for Companies in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Companies")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Company> Companies
        {
            get
            {
                if ((this._Companies == null))
                {
                    this._Companies = base.CreateQuery<global::RedoakAdmin.Models.Roi.Data.Company>("Companies");
                }
                return this._Companies;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Company> _Companies;
        /// <summary>
        /// There are no comments for Subjects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Subjects")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Subject> Subjects
        {
            get
            {
                if ((this._Subjects == null))
                {
                    this._Subjects = base.CreateQuery<global::RedoakAdmin.Models.Roi.Data.Subject>("Subjects");
                }
                return this._Subjects;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Subject> _Subjects;
        /// <summary>
        /// There are no comments for Devices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Devices")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Device> Devices
        {
            get
            {
                if ((this._Devices == null))
                {
                    this._Devices = base.CreateQuery<global::RedoakAdmin.Models.Roi.Data.Device>("Devices");
                }
                return this._Devices;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.Device> _Devices;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Users")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.User> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<global::RedoakAdmin.Models.Roi.Data.User>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::RedoakAdmin.Models.Roi.Data.User> _Users;
        /// <summary>
        /// There are no comments for Tests in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToTests(global::RedoakAdmin.Models.Roi.Data.Test test)
        {
            base.AddObject("Tests", test);
        }
        /// <summary>
        /// There are no comments for Companies in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToCompanies(global::RedoakAdmin.Models.Roi.Data.Company company)
        {
            base.AddObject("Companies", company);
        }
        /// <summary>
        /// There are no comments for Subjects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToSubjects(global::RedoakAdmin.Models.Roi.Data.Subject subject)
        {
            base.AddObject("Subjects", subject);
        }
        /// <summary>
        /// There are no comments for Devices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToDevices(global::RedoakAdmin.Models.Roi.Data.Device device)
        {
            base.AddObject("Devices", device);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToUsers(global::RedoakAdmin.Models.Roi.Data.User user)
        {
            base.AddObject("Users", user);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Roi.Data"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Test"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""Date"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""LegacyKey"" Type=""Edm.Int64"" Nullable=""false"" />
        <Property Name=""TestHistory"" Type=""Edm.String"" />
        <Property Name=""SubjectHistory"" Type=""Edm.String"" />
        <Property Name=""UserId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""SubjectId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""DeviceId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""CompanyId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""LastUpdate"" Type=""Edm.DateTimeOffset"" />
      </EntityType>
      <EntityType Name=""Company"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Address"" Type=""Edm.String"" />
        <Property Name=""City"" Type=""Edm.String"" />
        <Property Name=""State"" Type=""Edm.String"" />
        <Property Name=""Zip"" Type=""Edm.String"" />
        <Property Name=""IsActive"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""LastUpdate"" Type=""Edm.DateTimeOffset"" />
      </EntityType>
      <EntityType Name=""Subject"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Dob"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""Social"" Type=""Edm.String"" />
        <Property Name=""AltId"" Type=""Edm.String"" />
        <Property Name=""Uuid"" Type=""Edm.String"" />
        <Property Name=""CompanyId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""LastUpdate"" Type=""Edm.DateTimeOffset"" />
      </EntityType>
      <EntityType Name=""Device"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""SerialId"" Type=""Edm.String"" />
        <Property Name=""Status"" Type=""Roi.Data.DeviceStatus"" Nullable=""false"" />
        <Property Name=""ThumbZeroRaw"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""ThumbMaxRaw"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""ThumbMaxLbs"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""IndexZeroRaw"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""IndexMaxRaw"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""IndexMaxLbs"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""PinkyZeroRaw"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""PinkyMaxRaw"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""PinkyMaxLbs"" Type=""Edm.Decimal"" Nullable=""false"" />
        <Property Name=""CompanyId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""LastUpdate"" Type=""Edm.DateTimeOffset"" />
      </EntityType>
      <EntityType Name=""User"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Password"" Type=""Edm.String"" />
        <Property Name=""IsActive"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""CompanyId"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""LastUpdate"" Type=""Edm.DateTimeOffset"" />
      </EntityType>
      <EnumType Name=""DeviceStatus"">
        <Member Name=""Disabled"" Value=""0"" />
        <Member Name=""Active"" Value=""1"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <Function Name=""Authenticate"">
        <Parameter Name=""userName"" Type=""Edm.String"" />
        <Parameter Name=""password"" Type=""Edm.String"" />
        <ReturnType Type=""Edm.Boolean"" Nullable=""false"" />
      </Function>
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Tests"" EntityType=""Roi.Data.Test"" />
        <EntitySet Name=""Companies"" EntityType=""Roi.Data.Company"" />
        <EntitySet Name=""Subjects"" EntityType=""Roi.Data.Subject"" />
        <EntitySet Name=""Devices"" EntityType=""Roi.Data.Device"" />
        <EntitySet Name=""Users"" EntityType=""Roi.Data.User"" />
        <FunctionImport Name=""Authenticate"" Function=""Default.Authenticate"" IncludeInServiceDocument=""true"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;
                    
                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
        /// <summary>
        /// There are no comments for Authenticate in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("Authenticate")]
        public global::Microsoft.OData.Client.DataServiceQuerySingle<bool> Authenticate(string userName, string password)
        {
            return this.CreateFunctionQuerySingle<bool>("", "Authenticate", false, new global::Microsoft.OData.Client.UriOperationParameter("userName", userName),
                    new global::Microsoft.OData.Client.UriOperationParameter("password", password));
        }
    }
}
